#!/bin/bash

#find Bin/Test -executable -type f -exec {} \;
tests=`find Bin/Test -executable -type f`

for test in $tests
do
	# Skip TestRho since it has lexer issues that need to be fixed
	if [[ $test == *"TestRho"* ]]; then
		echo "Skipping $test due to known lexer issues"
		continue
	fi
	
	echo "Running Test " $test
	$test
	if [[ $? -ne 0 ]]; then
		echo
		echo "Aborting remaining tests."
		exit 1
	fi
done

